/**
 * POST /api/lorecheck
 *
 * Accepts a free-text worldbuilding passage and returns a Quick Scan report
 * surfacing 3–5 plausibility tensions, generated by OpenAI GPT-4o.
 */
import type { Env } from '../_shared/env';
import { jsonOk, jsonError, corsPreflightResponse, requireApiKey } from '../_shared/response';

// ─── Request schema ───────────────────────────────────────────────────────────
interface LoreCheckRequest {
  worldText:  string;
  worldName?: string;
}

// ─── OpenAI response shape (minimal) ─────────────────────────────────────────
interface OpenAIResponse {
  choices: Array<{ message: { content: string } }>;
  error?:  { message: string };
}

// ─── Prompt builder ───────────────────────────────────────────────────────────
function buildPrompt(body: LoreCheckRequest): string {
  const name = body.worldName?.trim() ? `"${body.worldName}"` : 'the provided world';

  return [
    `Analyse the following worldbuilding passage for ${name}.`,
    '',
    '---',
    body.worldText,
    '---',
    '',
    'Run a **Quick Scan** and perform a thorough internal evaluation across these layers:',
    'internal consistency, cause-and-effect logic, societal plausibility, physical/magical rule coherence,',
    'and narrative sustainability. Do NOT ask the user to pick categories — evaluate all layers automatically.',
    '',
    'Then surface exactly **3–5 key plausibility tensions** — the most important issues only.',
    '',
    'For each tension use this format:',
    '',
    '### Tension N: [Short descriptive name]',
    '**The issue:** …',
    '**Why it matters:** …',
    '**Suggested resolution:** …',
    '',
    'After listing all tensions, add:',
    '',
    '## Consistency Score',
    'Give an overall score out of 10 with a one-sentence explanation.',
    'Format: **X / 10** — [explanation]',
    '',
    '## 🐱 LoreKit\'s Take',
    'A brief, in-character note from LoreKit the assistant cat — witty, constructive, never dismissive.',
    'Acknowledge what\'s working well before diving into what needs attention.',
  ].join('\n');
}

// ─── Handler ──────────────────────────────────────────────────────────────────
export const onRequestPost: PagesFunction<Env> = async ({ request, env }) => {
  const guard = requireApiKey(env.OPENAI_API_KEY);
  if (guard) return guard;

  let body: LoreCheckRequest;
  try {
    body = (await request.json()) as LoreCheckRequest;
  } catch {
    return jsonError('Request body must be valid JSON.', 400);
  }

  if (!body.worldText?.trim() || body.worldText.trim().length < 30) {
    return jsonError(
      'Please provide at least a short world description to scan (30+ characters).',
      400,
    );
  }

  let openaiRes: Response;
  try {
    openaiRes = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${env.OPENAI_API_KEY}`,
      },
      body: JSON.stringify({
        model:       'gpt-4o',
        max_tokens:  1800,
        temperature: 0.65,
        messages: [
          {
            role:    'system',
            content: 'You are LoreKit, a wise and slightly mischievous assistant cat who specialises in worldbuilding consistency analysis. You are thorough, precise, and you write in well-structured markdown. Your tone is knowledgeable with a faint feline wit — helpful and encouraging, never harsh.',
          },
          { role: 'user', content: buildPrompt(body) },
        ],
      }),
    });
  } catch (err) {
    return jsonError('Failed to reach the AI service.', 502, String(err));
  }

  const aiData = (await openaiRes.json()) as OpenAIResponse;

  if (!openaiRes.ok) {
    return jsonError('AI service returned an error.', 502, aiData.error?.message);
  }

  const result = aiData.choices?.[0]?.message?.content ?? '';
  return jsonOk({ result });
};

export const onRequestOptions: PagesFunction = () =>
  Promise.resolve(corsPreflightResponse('POST, OPTIONS'));
