/**
 * POST /api/lorecraft
 *
 * Accepts a structured worldbuilding form and returns a deep verification
 * report generated by OpenAI GPT-4o.
 */
import type { Env } from '../_shared/env';
import { jsonOk, jsonError, corsPreflightResponse, requireApiKey } from '../_shared/response';

// ─── Request schema ───────────────────────────────────────────────────────────
interface LoreCraftRequest {
  worldType:         string;
  realityAnchor:     string;
  allowedDeviations: string;
  motif?:            string;
  extraContext?:     string;
}

// ─── OpenAI response shape (minimal) ─────────────────────────────────────────
interface OpenAIResponse {
  choices: Array<{ message: { content: string } }>;
  error?:  { message: string };
}

// ─── Prompt builder ───────────────────────────────────────────────────────────
function buildPrompt(body: LoreCraftRequest): string {
  const lines: string[] = [
    'Please generate a comprehensive worldbuilding verification report for the following world.',
    '',
    `**World Type:** ${body.worldType}`,
    '',
    '**Reality Anchor** (rules that always hold):',
    body.realityAnchor,
    '',
    '**Allowed Deviations** (what breaks or bends the rules):',
    body.allowedDeviations,
  ];

  if (body.motif?.trim()) {
    lines.push('', `**Core Motif / Themes:** ${body.motif}`);
  }
  if (body.extraContext?.trim()) {
    lines.push('', '**Additional Context:**', body.extraContext);
  }

  lines.push(
    '', '---', '',
    'Structure your report with the following sections (use markdown headers):',
    '',
    '## World Overview',
    "A brief, evocative synthesis of the world's essence and feel.",
    '',
    '## Internal Logic Assessment',
    "How coherently do the defined rules hold together? What's strong? What's fragile?",
    '',
    '## Key World Laws',
    'The fundamental rules governing this world — list 5–7 as bullet points.',
    '',
    '## Potential Tensions & Paradoxes',
    'Contradictions or unresolved questions the creator should address — list 3–5.',
    '',
    '## Narrative Opportunities',
    'Rich story hooks and thematic possibilities this world naturally generates — list 4–6.',
    '',
    '## Worldbuilder\'s Checklist',
    'Key questions to answer before writing in this world — list 5–8 as checkboxes (- [ ] …).',
    '',
    '## 🐱 LoreKit\'s Verdict',
    'A brief in-character verdict from LoreKit the assistant cat — knowledgeable, a little witty, warm. End with a star rating out of 5 (e.g. ✦✦✦✦☆ 4/5 — Solid foundations, a few loose stones).',
  );

  return lines.join('\n');
}

// ─── Handler ──────────────────────────────────────────────────────────────────
export const onRequestPost: PagesFunction<Env> = async ({ request, env }) => {
  const guard = requireApiKey(env.OPENAI_API_KEY);
  if (guard) return guard;

  let body: LoreCraftRequest;
  try {
    body = (await request.json()) as LoreCraftRequest;
  } catch {
    return jsonError('Request body must be valid JSON.', 400);
  }

  if (!body.worldType || !body.realityAnchor?.trim() || !body.allowedDeviations?.trim()) {
    return jsonError(
      'Missing required fields: worldType, realityAnchor, allowedDeviations.',
      400,
    );
  }

  let openaiRes: Response;
  try {
    openaiRes = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${env.OPENAI_API_KEY}`,
      },
      body: JSON.stringify({
        model:       'gpt-4o',
        max_tokens:  2200,
        temperature: 0.72,
        messages: [
          {
            role:    'system',
            content: 'You are LoreKit, a wise and slightly mischievous assistant cat who serves as a worldbuilding guide for writers and creators. You are knowledgeable, insightful, and speak with elegant precision — not childish, not gothic. You write in well-structured markdown. Your verdicts are warm but honest.',
          },
          { role: 'user', content: buildPrompt(body) },
        ],
      }),
    });
  } catch (err) {
    return jsonError('Failed to reach the AI service.', 502, String(err));
  }

  const aiData = (await openaiRes.json()) as OpenAIResponse;

  if (!openaiRes.ok) {
    return jsonError('AI service returned an error.', 502, aiData.error?.message);
  }

  const result = aiData.choices?.[0]?.message?.content ?? '';
  return jsonOk({ result });
};

export const onRequestOptions: PagesFunction = () =>
  Promise.resolve(corsPreflightResponse('POST, OPTIONS'));
