/**
 * POST /api/simulator
 *
 * Accepts a visitor name + optional vibe and returns a character story card
 * from one of the preset LoreKit worlds, generated by OpenAI GPT-4o.
 */
import type { Env } from '../_shared/env';
import { jsonOk, jsonError, corsPreflightResponse, requireApiKey } from '../_shared/response';

// ─── Request schema ───────────────────────────────────────────────────────────
interface SimulatorRequest {
  name:       string;
  vibe?:      string;
  worldHint?: string;
}

// ─── OpenAI response shape (minimal) ─────────────────────────────────────────
interface OpenAIResponse {
  choices: Array<{ message: { content: string } }>;
  error?:  { message: string };
}

// ─── Preset worlds ────────────────────────────────────────────────────────────
const WORLDS = [
  'The Forgotten Archives',
  'The Neon Depths',
  'The Emberfall Kingdom',
  'The Drift Between Stars',
  'The Verdant Labyrinth',
] as const;

// ─── Prompt builder ───────────────────────────────────────────────────────────
function buildPrompt(name: string, vibe?: string, worldHint?: string): string {
  const worldLine = worldHint?.trim()
    ? `The visitor has a feeling they belong in **${worldHint}**.`
    : `Assign them to one of these worlds based on their vibe: ${WORLDS.join(', ')}.`;

  const vibeLine = vibe?.trim()
    ? `Their vibe: "${vibe}".`
    : 'They have revealed nothing about themselves — let the world surprise them.';

  return [
    `A wanderer named **${name}** has stepped through the LoreKit portal.`,
    vibeLine,
    worldLine,
    '',
    'Write their character card (150–220 words) following this structure:',
    '',
    '1. **World & Title** — State the world and give them a specific, evocative title/role in that world.',
    '2. **First Arrival** — Describe their first vivid moment stepping into this world. Make it cinematic.',
    '3. **Gift & Shadow** — One remarkable ability or trait they possess; one secret burden they carry.',
    '4. **The Prophecy** — End with a single-sentence prophecy or quest hook written in archaic style.',
    '',
    `Tone: mythic, poetic, confident. Make ${name} feel chosen. Keep it under 230 words.`,
    '',
    'Also output on the very last line, separated by "---", the world name you assigned:',
    '---',
    'WORLD: [world name here]',
  ].join('\n');
}

// ─── Handler ──────────────────────────────────────────────────────────────────
export const onRequestPost: PagesFunction<Env> = async ({ request, env }) => {
  const guard = requireApiKey(env.OPENAI_API_KEY);
  if (guard) return guard;

  let body: SimulatorRequest;
  try {
    body = (await request.json()) as SimulatorRequest;
  } catch {
    return jsonError('Request body must be valid JSON.', 400);
  }

  if (!body.name?.trim()) {
    return jsonError('A name is required to open the portal.', 400);
  }

  // Sanitise: cap name length to prevent prompt injection via oversized strings
  const safeName = body.name.trim().slice(0, 80);

  let openaiRes: Response;
  try {
    openaiRes = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${env.OPENAI_API_KEY}`,
      },
      body: JSON.stringify({
        model:       'gpt-4o',
        max_tokens:  500,
        temperature: 0.88,
        messages: [
          {
            role:    'system',
            content: 'You are LoreKit, a magical assistant cat who writes character cards for wanderers stepping through interdimensional portals. Your writing is mythic, evocative, and poetic — like a fantasy novel opening. You always make the visitor feel significant and special.',
          },
          { role: 'user', content: buildPrompt(safeName, body.vibe, body.worldHint) },
        ],
      }),
    });
  } catch (err) {
    return jsonError('Failed to reach the AI service.', 502, String(err));
  }

  const aiData = (await openaiRes.json()) as OpenAIResponse;

  if (!openaiRes.ok) {
    return jsonError('AI service returned an error.', 502, aiData.error?.message);
  }

  const raw = aiData.choices?.[0]?.message?.content ?? '';

  // Extract world name appended after the final "---" separator
  const parts     = raw.split('---');
  const storyPart = parts.slice(0, -1).join('---').trim() || raw.trim();
  const lastPart  = parts[parts.length - 1] ?? '';
  const worldMatch = lastPart.match(/WORLD:\s*(.+)/);
  const world      = worldMatch ? worldMatch[1].trim() : '';

  return jsonOk({ result: storyPart, world });
};

export const onRequestOptions: PagesFunction = () =>
  Promise.resolve(corsPreflightResponse('POST, OPTIONS'));
