import { useState, useRef } from 'react';
import type { SimulatorCard, SimulatorForm, VibeType } from '../types/simulator';
import { useLang } from '../i18n';
import type { TranslationKey } from '../i18n';
import { useAuth } from '../contexts/AuthContext';
import { saveReport } from '../lib/library';

// ─── World metadata lookup (matches the 12 preset worlds in the backend) ──────
const WORLD_META: Record<string, { emoji: string; tagline: string }> = {
  'The Hollow Crown':        { emoji: '👑', tagline: 'A kingdom whose king died and left only his expectations behind.' },
  'The Neon Depths':         { emoji: '⚡', tagline: 'A bioluminescent city beneath a toxic sea where survival is commerce.' },
  'The Ashborne Wastes':     { emoji: '🏜️', tagline: 'A post-collapse desert civilisation where memory is contraband.' },
  'The Saltwater Sanctum':   { emoji: '🌊', tagline: 'A hidden island community of retired spellweavers who swore to rest.' },
  'The Verdant Labyrinth':   { emoji: '🌿', tagline: 'A living forest-maze that rearranges itself to guide — or to mislead.' },
  'The Moonlit Carnival':    { emoji: '🌙', tagline: 'An eternal travelling carnival that exists slightly outside of time.' },
  'The Emberfall Kingdom':   { emoji: '🔥', tagline: 'A realm where the sun set permanently and warmth is slowly running out.' },
  'The Drift Between Stars': { emoji: '✦',  tagline: 'A nomadic fleet culture in deep space where everyone is the last of something.' },
  'The Forgotten Archives':  { emoji: '📚', tagline: 'An interdimensional library where lost memories and unwritten books go to die.' },
  'The Gossamer Veil':       { emoji: '🕸️', tagline: 'The shimmering border between dreams and waking, inhabited by both.' },
  'The Clockwork Wilds':     { emoji: '⚙️', tagline: 'A forest of mechanical animals and organic machines in fragile coexistence.' },
  'The Upside Market':       { emoji: '🪄', tagline: 'A floating bazaar where impossible goods are bought, sold, and occasionally stolen back.' },
};

function getWorldMeta(name: string) {
  return WORLD_META[name] ?? { emoji: '🌌', tagline: 'A world between worlds.' };
}

// ─── Vibe config ──────────────────────────────────────────────────────────────
const VIBES: Array<{ key: VibeType; labelKey: TranslationKey; icon: string; hintKey: TranslationKey }> = [
  { key: 'dark',      labelKey: 'vibe_dark_label',      icon: '🌑', hintKey: 'vibe_dark_hint' },
  { key: 'cozy',      labelKey: 'vibe_cozy_label',      icon: '🕯',  hintKey: 'vibe_cozy_hint' },
  { key: 'tragic',    labelKey: 'vibe_tragic_label',    icon: '🥀',  hintKey: 'vibe_tragic_hint' },
  { key: 'whimsical', labelKey: 'vibe_whimsical_label', icon: '✨',  hintKey: 'vibe_whimsical_hint' },
];

// ─── Character card component ─────────────────────────────────────────────────
function CharacterCard({
  card,
  imageDataUrl,
  onTryAgain,
  onSave,
  saveState,
}: {
  card:         SimulatorCard;
  imageDataUrl: string | null;
  onTryAgain:   () => void;
  onSave?:      () => void;
  saveState?:   'idle' | 'saving' | 'saved' | 'error';
}) {
  const { t } = useLang();
  const [copied,          setCopied] = useState(false);
  const [showDownloadTip, setTip]    = useState(false);

  const worldMeta = getWorldMeta(card.assignedWorld);

  const plainText = [
    `— ${card.assignedWorld} —`,
    '',
    card.name.toUpperCase(),
    card.roleArchetype,
    '',
    card.storyHookLines.join(' '),
    '',
    `"${card.fateQuote}"`,
    '',
    'Generated by LoreKit 🐱',
  ].join('\n');

  async function handleCopy() {
    await navigator.clipboard.writeText(plainText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2200);
  }

  function handleShareX() {
    const shareText = [
      `I just got placed in ${card.assignedWorld} as ${card.roleArchetype}!`,
      '',
      `"${card.fateQuote}"`,
      '',
      '🐱 lorekit.cc/simulator',
    ].join('\n');
    const url = `https://x.com/intent/post?text=${encodeURIComponent(shareText)}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  }

  async function handleNativeShare() {
    try {
      await navigator.share({
        title: `${card.name} — ${card.assignedWorld}`,
        text:  plainText,
        url:   `${window.location.origin}/simulator`,
      });
    } catch {
      // user cancelled or browser unsupported — no-op
    }
  }

  return (
    <div className="sim-result animate-fade-up">

      {/* The shareable card */}
      <div
        className={`sim-card sim-card--${card.vibe || 'default'}`}
        data-vibe={card.vibe || 'default'}
      >
        {/* World header strip */}
        <div className="sim-card__world">
          <span className="sim-card__world-emoji">{worldMeta.emoji}</span>
          <div>
            <span className="sim-card__world-name">{card.assignedWorld}</span>
            <span className="sim-card__world-tagline">{worldMeta.tagline}</span>
          </div>
        </div>

        <div className="sim-card__divider" />

        {/* Portrait + identity */}
        <div className="sim-card__identity">
          {imageDataUrl ? (
            <img
              src={imageDataUrl}
              alt="Character portrait"
              className="sim-card__portrait"
            />
          ) : (
            <div className="sim-card__portrait-placeholder">
              <span>{worldMeta.emoji}</span>
            </div>
          )}
          <div className="sim-card__identity-text">
            <h2 className="sim-card__name">{card.name}</h2>
            <p className="sim-card__role">{card.roleArchetype}</p>
          </div>
        </div>

        <div className="sim-card__divider" />

        {/* Story hook */}
        <p className="sim-card__story">
          {card.storyHookLines.join(' ')}
        </p>

        {/* Fate quote */}
        <div className="sim-card__fate-block">
          <span className="sim-card__fate-rule" />
          <blockquote className="sim-card__fate">
            "{card.fateQuote}"
          </blockquote>
          <span className="sim-card__fate-rule" />
        </div>

        {/* LoreKit credit */}
        <p className="sim-card__credit">🐱 LoreKit</p>
      </div>

      {/* Actions below card */}
      <div className="sim-card-actions">
        <div className="sim-card-actions__left">
          <button className="btn btn-teal btn-sm" onClick={handleCopy}>
            {copied ? t('sim_copied') : t('sim_copy')}
          </button>

          {/* Share on X */}
          <button
            type="button"
            className="btn btn-ghost btn-sm sim-share-btn sim-share-btn--x"
            onClick={handleShareX}
            aria-label={t('sim_share_x')}
          >
            {t('sim_share_x')}
          </button>

          {/* Native share (mobile) */}
          {'share' in navigator && (
            <button
              type="button"
              className="btn btn-ghost btn-sm"
              onClick={handleNativeShare}
              aria-label={t('sim_share_native')}
            >
              {t('sim_share_native')}
            </button>
          )}

          <div
            className="sim-download-wrap"
            onMouseEnter={() => setTip(true)}
            onMouseLeave={() => setTip(false)}
          >
            <button
              type="button"
              className="btn btn-ghost btn-sm sim-download-btn"
              disabled
              aria-label={t('sim_download')}
            >
              {t('sim_download')}
              <span className="lc-coming-soon">{t('coming_soon')}</span>
            </button>
            {showDownloadTip && (
              <div className="sim-tooltip">
                {t('sim_download_tip')}
              </div>
            )}
          </div>
        </div>

        {onSave && (
          <button
            className="btn btn-ghost btn-sm"
            onClick={onSave}
            disabled={saveState === 'saving' || saveState === 'saved'}
          >
            {saveState === 'saved'
              ? t('save_to_library_done')
              : saveState === 'error'
              ? t('save_to_library_error')
              : t('save_to_library')}
          </button>
        )}
        <button className="btn btn-ghost btn-sm" onClick={onTryAgain}>
          {t('sim_try_again')}
        </button>
      </div>

    </div>
  );
}

// ─── Vibe chip ────────────────────────────────────────────────────────────────
function VibeChip({
  vibe,
  selected,
  onToggle,
}: {
  vibe:     typeof VIBES[number];
  selected: boolean;
  onToggle: () => void;
}) {
  const { t } = useLang();
  return (
    <button
      type="button"
      className={`sim-vibe-chip sim-vibe-chip--${vibe.key} ${selected ? 'sim-vibe-chip--selected' : ''}`}
      onClick={onToggle}
      title={t(vibe.hintKey)}
      aria-pressed={selected}
    >
      <span className="sim-vibe-chip__icon">{vibe.icon}</span>
      <span className="sim-vibe-chip__label">{t(vibe.labelKey)}</span>
    </button>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────
export default function Simulator() {
  const { t, lang } = useLang();
  const { user }    = useAuth();
  const fileRef = useRef<HTMLInputElement>(null);

  const [form,      setForm]      = useState<SimulatorForm>({ name: '', vibe: '', imageDataUrl: null });
  const [card,      setCard]      = useState<SimulatorCard | null>(null);
  const [loading,   setLoading]   = useState(false);
  const [error,     setError]     = useState<string | null>(null);
  const [saveState, setSaveState] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle');

  const canReveal = form.name.trim().length > 0 && form.name.trim().length <= 60;

  function handleImageChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () =>
      setForm(prev => ({ ...prev, imageDataUrl: reader.result as string }));
    reader.readAsDataURL(file);
  }

  function toggleVibe(key: VibeType) {
    setForm(prev => ({ ...prev, vibe: prev.vibe === key ? '' : key }));
  }

  async function handleReveal(e: React.FormEvent) {
    e.preventDefault();
    if (!canReveal || loading) return;
    setLoading(true);
    setCard(null);
    setError(null);

    try {
      const res = await fetch('/api/simulator', {
        method:  'POST',
        headers: {
          'Content-Type':   'application/json',
          'X-LoreKit-Lang': lang,
        },
        body: JSON.stringify({
          name: form.name.trim(),
          vibe: form.vibe || undefined,
          lang,
        }),
      });

      const data = await res.json() as Record<string, unknown>;

      if (!res.ok) {
        setError((data['error'] as string | undefined) ?? t('err_generic'));
      } else {
        setCard({ ...(data as Omit<SimulatorCard, 'vibe'>), vibe: form.vibe });
        setTimeout(() => {
          document.getElementById('sim-card-anchor')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }, 80);
      }
    } catch {
      setError(t('err_server'));
    } finally {
      setLoading(false);
    }
  }

  async function handleSave() {
    if (!card || !user) return;
    setSaveState('saving');
    const title = `${card.name} — ${card.assignedWorld}`;
    const { error: saveError } = await saveReport(user.id, 'simulator', title, card);
    setSaveState(saveError ? 'error' : 'saved');
  }

  function handleTryAgain() {
    setCard(null);
    setError(null);
    setSaveState('idle');
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  return (
    <div className="page-wrapper">

      {/* ── Page header ─────────────────────────────────────────────────── */}
      <section className="section-header animate-fade-up">
        <span className="eyebrow">✨ Simulator</span>
        <h1>{t('sim_title')}</h1>
        <p>{t('sim_desc')}</p>
      </section>

      {/* ── Form ────────────────────────────────────────────────────────── */}
      <div className="card animate-fade-up" style={{ animationDelay: '60ms' }}>
        <form onSubmit={handleReveal}>

          {/* Name */}
          <div className="form-group" style={{ marginBottom: '1.5rem' }}>
            <label className="form-label" htmlFor="simName">
              {t('sim_name_label')} <span style={{ color: 'var(--rose)' }}>*</span>
            </label>
            <input
              id="simName"
              type="text"
              className="form-input sim-name-input"
              placeholder={t('sim_name_placeholder')}
              value={form.name}
              maxLength={60}
              onChange={e => setForm(p => ({ ...p, name: e.target.value }))}
            />
          </div>

          {/* Vibe selector */}
          <div className="form-group" style={{ marginBottom: '1.5rem' }}>
            <p className="form-label" style={{ marginBottom: '0.6rem' }}>
              {t('sim_vibe_label')} <span className="optional">{t('sim_vibe_optional')}</span>
            </p>
            <div className="sim-vibe-group">
              {VIBES.map(v => (
                <VibeChip
                  key={v.key}
                  vibe={v}
                  selected={form.vibe === v.key}
                  onToggle={() => toggleVibe(v.key)}
                />
              ))}
            </div>
            {form.vibe && (
              <p className="form-hint sim-vibe-hint">
                {t(VIBES.find(v => v.key === form.vibe)!.hintKey)}
              </p>
            )}
          </div>

          {/* Portrait upload */}
          <div className="form-group" style={{ marginBottom: '1.5rem' }}>
            <p className="form-label" style={{ marginBottom: '0.5rem' }}>
              {t('sim_portrait_label')} <span className="optional">{t('sim_portrait_optional')}</span>
            </p>
            <div className="sim-upload-area">
              {form.imageDataUrl ? (
                <div className="sim-upload-area__preview">
                  <img
                    src={form.imageDataUrl}
                    alt="Portrait preview"
                    className="sim-upload-preview-img"
                  />
                  <div className="sim-upload-area__preview-actions">
                    <button
                      type="button"
                      className="btn btn-ghost btn-sm"
                      onClick={() => fileRef.current?.click()}
                    >
                      {t('sim_portrait_change')}
                    </button>
                    <button
                      type="button"
                      className="btn btn-ghost btn-sm"
                      onClick={() => setForm(p => ({ ...p, imageDataUrl: null }))}
                    >
                      {t('sim_portrait_remove')}
                    </button>
                  </div>
                </div>
              ) : (
                <button
                  type="button"
                  className="sim-upload-trigger"
                  onClick={() => fileRef.current?.click()}
                >
                  <span className="sim-upload-trigger__icon">🖼</span>
                  <span className="sim-upload-trigger__label">{t('sim_portrait_click')}</span>
                  <span className="sim-upload-trigger__hint">{t('sim_portrait_hint')}</span>
                </button>
              )}
              <input
                ref={fileRef}
                type="file"
                accept="image/*"
                onChange={handleImageChange}
                style={{ display: 'none' }}
              />
            </div>
          </div>

          {/* Submit */}
          <div className="form-actions">
            <button
              type="submit"
              className="btn btn-teal btn-lg sim-reveal-btn"
              disabled={!canReveal || loading}
            >
              {loading
                ? t('sim_revealing')
                : card
                ? t('sim_reveal_again')
                : t('sim_reveal')}
            </button>
          </div>
        </form>
      </div>

      {/* ── Loading ──────────────────────────────────────────────────────── */}
      {loading && (
        <div className="spinner-wrap">
          <div className="spinner" />
          <span>{t('sim_weaving')}</span>
        </div>
      )}

      {/* ── Error ────────────────────────────────────────────────────────── */}
      {error && !loading && (
        <div className="card animate-fade-up" style={{ marginTop: '1.5rem', borderColor: 'var(--rose)' }}>
          <p style={{ color: 'var(--rose)', margin: 0 }}>🐱 {error}</p>
        </div>
      )}

      {/* ── Character card ────────────────────────────────────────────────── */}
      {card && !loading && (
        <div id="sim-card-anchor" style={{ marginTop: '2.5rem' }}>
          <CharacterCard
            card={card}
            imageDataUrl={form.imageDataUrl}
            onTryAgain={handleTryAgain}
            onSave={user ? handleSave : undefined}
            saveState={saveState}
          />
        </div>
      )}

    </div>
  );
}
