import { useState, useRef } from 'react';
import type { SimulatorCard, SimulatorForm, VibeType } from '../types/simulator';

// ─── World metadata lookup (matches the 12 preset worlds in the backend) ──────
const WORLD_META: Record<string, { emoji: string; tagline: string }> = {
  'The Hollow Crown':        { emoji: '👑', tagline: 'A kingdom whose king died and left only his expectations behind.' },
  'The Neon Depths':         { emoji: '⚡', tagline: 'A bioluminescent city beneath a toxic sea where survival is commerce.' },
  'The Ashborne Wastes':     { emoji: '🏜️', tagline: 'A post-collapse desert civilisation where memory is contraband.' },
  'The Saltwater Sanctum':   { emoji: '🌊', tagline: 'A hidden island community of retired spellweavers who swore to rest.' },
  'The Verdant Labyrinth':   { emoji: '🌿', tagline: 'A living forest-maze that rearranges itself to guide — or to mislead.' },
  'The Moonlit Carnival':    { emoji: '🌙', tagline: 'An eternal travelling carnival that exists slightly outside of time.' },
  'The Emberfall Kingdom':   { emoji: '🔥', tagline: 'A realm where the sun set permanently and warmth is slowly running out.' },
  'The Drift Between Stars': { emoji: '✦',  tagline: 'A nomadic fleet culture in deep space where everyone is the last of something.' },
  'The Forgotten Archives':  { emoji: '📚', tagline: 'An interdimensional library where lost memories and unwritten books go to die.' },
  'The Gossamer Veil':       { emoji: '🕸️', tagline: 'The shimmering border between dreams and waking, inhabited by both.' },
  'The Clockwork Wilds':     { emoji: '⚙️', tagline: 'A forest of mechanical animals and organic machines in fragile coexistence.' },
  'The Upside Market':       { emoji: '🪄', tagline: 'A floating bazaar where impossible goods are bought, sold, and occasionally stolen back.' },
};

function getWorldMeta(name: string) {
  return WORLD_META[name] ?? { emoji: '🌌', tagline: 'A world between worlds.' };
}

// ─── Vibe config ──────────────────────────────────────────────────────────────
const VIBES: Array<{ key: VibeType; label: string; icon: string; hint: string }> = [
  { key: 'dark',      label: 'Dark',      icon: '🌑', hint: 'Shadow, secrets, cost' },
  { key: 'cozy',      label: 'Cozy',      icon: '🕯',  hint: 'Warmth, belonging, slow magic' },
  { key: 'tragic',    label: 'Tragic',    icon: '🥀',  hint: 'Loss, duty, last chances' },
  { key: 'whimsical', label: 'Whimsical', icon: '✨',  hint: 'Chaos, wonder, unlikely heroes' },
];

// ─── Character card component ─────────────────────────────────────────────────
function CharacterCard({
  card,
  imageDataUrl,
  onTryAgain,
}: {
  card:         SimulatorCard;
  imageDataUrl: string | null;
  onTryAgain:   () => void;
}) {
  const [copied,          setCopied] = useState(false);
  const [showDownloadTip, setTip]    = useState(false);

  const worldMeta = getWorldMeta(card.assignedWorld);

  const plainText = [
    `— ${card.assignedWorld} —`,
    '',
    card.name.toUpperCase(),
    card.roleArchetype,
    '',
    card.storyHookLines.join(' '),
    '',
    `"${card.fateQuote}"`,
    '',
    'Generated by LoreKit 🐱',
  ].join('\n');

  async function handleCopy() {
    await navigator.clipboard.writeText(plainText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2200);
  }

  return (
    <div className="sim-result animate-fade-up">

      {/* The shareable card */}
      <div
        className={`sim-card sim-card--${card.vibe || 'default'}`}
        data-vibe={card.vibe || 'default'}
      >
        {/* World header strip */}
        <div className="sim-card__world">
          <span className="sim-card__world-emoji">{worldMeta.emoji}</span>
          <div>
            <span className="sim-card__world-name">{card.assignedWorld}</span>
            <span className="sim-card__world-tagline">{worldMeta.tagline}</span>
          </div>
        </div>

        <div className="sim-card__divider" />

        {/* Portrait + identity */}
        <div className="sim-card__identity">
          {imageDataUrl ? (
            <img
              src={imageDataUrl}
              alt="Character portrait"
              className="sim-card__portrait"
            />
          ) : (
            <div className="sim-card__portrait-placeholder">
              <span>{worldMeta.emoji}</span>
            </div>
          )}
          <div className="sim-card__identity-text">
            <h2 className="sim-card__name">{card.name}</h2>
            <p className="sim-card__role">{card.roleArchetype}</p>
          </div>
        </div>

        <div className="sim-card__divider" />

        {/* Story hook */}
        <p className="sim-card__story">
          {card.storyHookLines.join(' ')}
        </p>

        {/* Fate quote */}
        <div className="sim-card__fate-block">
          <span className="sim-card__fate-rule" />
          <blockquote className="sim-card__fate">
            "{card.fateQuote}"
          </blockquote>
          <span className="sim-card__fate-rule" />
        </div>

        {/* LoreKit credit */}
        <p className="sim-card__credit">🐱 LoreKit</p>
      </div>

      {/* Actions below card */}
      <div className="sim-card-actions">
        <div className="sim-card-actions__left">
          <button className="btn btn-teal btn-sm" onClick={handleCopy}>
            {copied ? '✅ Copied!' : '📋 Copy text'}
          </button>

          <div
            className="sim-download-wrap"
            onMouseEnter={() => setTip(true)}
            onMouseLeave={() => setTip(false)}
          >
            <button
              type="button"
              className="btn btn-ghost btn-sm sim-download-btn"
              disabled
              aria-label="Download card as image — coming soon"
            >
              🖼 Download card
              <span className="lc-coming-soon">soon</span>
            </button>
            {showDownloadTip && (
              <div className="sim-tooltip">
                Image export is coming in a future release.
              </div>
            )}
          </div>
        </div>

        <button className="btn btn-ghost btn-sm" onClick={onTryAgain}>
          ↺ Try again
        </button>
      </div>

    </div>
  );
}

// ─── Vibe chip ────────────────────────────────────────────────────────────────
function VibeChip({
  vibe,
  selected,
  onToggle,
}: {
  vibe:     typeof VIBES[number];
  selected: boolean;
  onToggle: () => void;
}) {
  return (
    <button
      type="button"
      className={`sim-vibe-chip sim-vibe-chip--${vibe.key} ${selected ? 'sim-vibe-chip--selected' : ''}`}
      onClick={onToggle}
      title={vibe.hint}
      aria-pressed={selected}
    >
      <span className="sim-vibe-chip__icon">{vibe.icon}</span>
      <span className="sim-vibe-chip__label">{vibe.label}</span>
    </button>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────
export default function Simulator() {
  const fileRef = useRef<HTMLInputElement>(null);

  const [form,    setForm]    = useState<SimulatorForm>({ name: '', vibe: '', imageDataUrl: null });
  const [card,    setCard]    = useState<SimulatorCard | null>(null);
  const [loading, setLoading] = useState(false);
  const [error,   setError]   = useState<string | null>(null);

  const canReveal = form.name.trim().length > 0 && form.name.trim().length <= 60;

  function handleImageChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () =>
      setForm(prev => ({ ...prev, imageDataUrl: reader.result as string }));
    reader.readAsDataURL(file);
  }

  function toggleVibe(key: VibeType) {
    setForm(prev => ({ ...prev, vibe: prev.vibe === key ? '' : key }));
  }

  async function handleReveal(e: React.FormEvent) {
    e.preventDefault();
    if (!canReveal || loading) return;
    setLoading(true);
    setCard(null);
    setError(null);

    try {
      const res = await fetch('/api/simulator', {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body:    JSON.stringify({
          name: form.name.trim(),
          vibe: form.vibe || undefined,
        }),
      });

      const data = await res.json() as Record<string, unknown>;

      if (!res.ok) {
        setError((data['error'] as string | undefined) ?? 'Something went wrong. Please try again.');
      } else {
        // Merge API response with client-side vibe for card styling
        setCard({ ...(data as Omit<SimulatorCard, 'vibe'>), vibe: form.vibe });
        setTimeout(() => {
          document.getElementById('sim-card-anchor')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }, 80);
      }
    } catch {
      setError('Could not reach the server. Check your connection and try again.');
    } finally {
      setLoading(false);
    }
  }

  function handleTryAgain() {
    setCard(null);
    setError(null);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  return (
    <div className="page-wrapper">

      {/* ── Page header ─────────────────────────────────────────────────── */}
      <section className="section-header animate-fade-up">
        <span className="eyebrow">✨ Simulator</span>
        <h1>Step Through the Portal</h1>
        <p>
          Enter your name, choose a vibe, add a portrait. LoreKit will summon your character
          card from one of the ancient worlds. Free, instant, and made for sharing.
        </p>
      </section>

      {/* ── Form ────────────────────────────────────────────────────────── */}
      <div className="card animate-fade-up" style={{ animationDelay: '60ms' }}>
        <form onSubmit={handleReveal}>

          {/* Name */}
          <div className="form-group" style={{ marginBottom: '1.5rem' }}>
            <label className="form-label" htmlFor="simName">
              Your Name <span style={{ color: 'var(--rose)' }}>*</span>
            </label>
            <input
              id="simName"
              type="text"
              className="form-input sim-name-input"
              placeholder="What shall we call you, wanderer?"
              value={form.name}
              maxLength={60}
              onChange={e => setForm(p => ({ ...p, name: e.target.value }))}
            />
          </div>

          {/* Vibe selector */}
          <div className="form-group" style={{ marginBottom: '1.5rem' }}>
            <p className="form-label" style={{ marginBottom: '0.6rem' }}>
              Vibe <span className="optional">(optional — shapes your world)</span>
            </p>
            <div className="sim-vibe-group">
              {VIBES.map(v => (
                <VibeChip
                  key={v.key}
                  vibe={v}
                  selected={form.vibe === v.key}
                  onToggle={() => toggleVibe(v.key)}
                />
              ))}
            </div>
            {form.vibe && (
              <p className="form-hint sim-vibe-hint">
                {VIBES.find(v => v.key === form.vibe)?.hint}
              </p>
            )}
          </div>

          {/* Portrait upload */}
          <div className="form-group" style={{ marginBottom: '1.5rem' }}>
            <p className="form-label" style={{ marginBottom: '0.5rem' }}>
              Portrait <span className="optional">(optional — client-side only, never uploaded)</span>
            </p>
            <div className="sim-upload-area">
              {form.imageDataUrl ? (
                <div className="sim-upload-area__preview">
                  <img
                    src={form.imageDataUrl}
                    alt="Portrait preview"
                    className="sim-upload-preview-img"
                  />
                  <div className="sim-upload-area__preview-actions">
                    <button
                      type="button"
                      className="btn btn-ghost btn-sm"
                      onClick={() => fileRef.current?.click()}
                    >
                      Change
                    </button>
                    <button
                      type="button"
                      className="btn btn-ghost btn-sm"
                      onClick={() => setForm(p => ({ ...p, imageDataUrl: null }))}
                    >
                      Remove
                    </button>
                  </div>
                </div>
              ) : (
                <button
                  type="button"
                  className="sim-upload-trigger"
                  onClick={() => fileRef.current?.click()}
                >
                  <span className="sim-upload-trigger__icon">🖼</span>
                  <span className="sim-upload-trigger__label">Click to add a portrait</span>
                  <span className="sim-upload-trigger__hint">JPG, PNG, WebP — displayed on card only</span>
                </button>
              )}
              <input
                ref={fileRef}
                type="file"
                accept="image/*"
                onChange={handleImageChange}
                style={{ display: 'none' }}
              />
            </div>
          </div>

          {/* Submit */}
          <div className="form-actions">
            <button
              type="submit"
              className="btn btn-teal btn-lg sim-reveal-btn"
              disabled={!canReveal || loading}
            >
              {loading
                ? '🌀 The portal is opening…'
                : card
                ? '✨ Reveal again'
                : '✨ Reveal my role'}
            </button>
          </div>
        </form>
      </div>

      {/* ── Loading ──────────────────────────────────────────────────────── */}
      {loading && (
        <div className="spinner-wrap">
          <div className="spinner" />
          <span>The portal is weaving your fate…</span>
        </div>
      )}

      {/* ── Error ────────────────────────────────────────────────────────── */}
      {error && !loading && (
        <div className="card animate-fade-up" style={{ marginTop: '1.5rem', borderColor: 'var(--rose)' }}>
          <p style={{ color: 'var(--rose)', margin: 0 }}>🐱 {error}</p>
        </div>
      )}

      {/* ── Character card ────────────────────────────────────────────────── */}
      {card && !loading && (
        <div id="sim-card-anchor" style={{ marginTop: '2.5rem' }}>
          <CharacterCard
            card={card}
            imageDataUrl={form.imageDataUrl}
            onTryAgain={handleTryAgain}
          />
        </div>
      )}

    </div>
  );
}
